name: Publish to npm
on: registry_package
jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
          scope: getify
      - run: "echo \"repo_token: ${{secrets.coveralls_token}}\" > .coveralls.yml"
      - run: npm install && npm --userconfig='/home/runner/work/_temp/.npmrc' publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
